# fly.toml app configuration file generated for fastapi-deployment on 2025-07-26T17:53:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-deployment'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
